name = "reverie-the-game"
main = "server/src/index.ts"
compatibility_date = "2026-01-01"
workers_dev = true

[assets]
directory = "./site"
binding = "ASSETS"

[durable_objects]
bindings = [{ name = "WORLD", class_name = "ReverieWorld" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReverieWorld"]
